-- A2Z Training Scheduler: PostgreSQL 16 schema
--
-- This is deliberately a new-database schema. Do not run it against the
-- live SQLite application. It is applied only to the new PostgreSQL database
-- during the KVM 8 migration.

BEGIN;

CREATE TABLE IF NOT EXISTS branches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    address TEXT,
    phone TEXT,
    is_active INTEGER NOT NULL DEFAULT 1,
    timezone TEXT NOT NULL DEFAULT 'Asia/Kolkata',
    currency TEXT NOT NULL DEFAULT 'INR',
    reminder_channel TEXT NOT NULL DEFAULT 'email'
);

CREATE TABLE IF NOT EXISTS machines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    machine_code TEXT UNIQUE NOT NULL,
    category TEXT NOT NULL,
    location TEXT,
    branch_id BIGINT NOT NULL REFERENCES branches(id),
    is_active INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS instructors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    branch_id BIGINT NOT NULL REFERENCES branches(id),
    specialty TEXT,
    is_active INTEGER NOT NULL DEFAULT 1,
    verification_status TEXT NOT NULL DEFAULT 'unverified',
    verified_at TEXT,
    verified_by BIGINT,
    uses_custom_availability INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
    display_order INTEGER NOT NULL DEFAULT 1000,
    UNIQUE (name, branch_id),
    CHECK (verification_status IN ('unverified', 'verified'))
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'student',
    instructor_id BIGINT REFERENCES instructors(id) DEFERRABLE INITIALLY DEFERRED,
    full_name TEXT,
    email TEXT,
    phone TEXT,
    branch_id BIGINT REFERENCES branches(id),
    is_super_admin INTEGER NOT NULL DEFAULT 0,
    is_active INTEGER NOT NULL DEFAULT 1,
    login_enabled INTEGER NOT NULL DEFAULT 1,
    must_change_password INTEGER NOT NULL DEFAULT 1,
    deactivated_at TEXT,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
    permission_mask INTEGER,
    CHECK (role IN ('student', 'booking_agent', 'instructor', 'admin')),
    CHECK ((role = 'instructor' AND instructor_id IS NOT NULL)
        OR (role <> 'instructor' AND instructor_id IS NULL))
);
DO $$
BEGIN
    ALTER TABLE instructors
        ADD CONSTRAINT instructors_verified_by_fkey
        FOREIGN KEY (verified_by) REFERENCES users(id) DEFERRABLE INITIALLY DEFERRED;
EXCEPTION WHEN duplicate_object THEN
    NULL;
END $$;

CREATE TABLE IF NOT EXISTS services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id BIGINT NOT NULL REFERENCES branches(id),
    name TEXT NOT NULL,
    description TEXT,
    category TEXT,
    duration_minutes INTEGER NOT NULL DEFAULT 30,
    price_cents INTEGER NOT NULL DEFAULT 0,
    currency TEXT NOT NULL DEFAULT 'INR',
    buffer_before_minutes INTEGER NOT NULL DEFAULT 0,
    buffer_after_minutes INTEGER NOT NULL DEFAULT 0,
    color TEXT NOT NULL DEFAULT '#C8141B',
    available_weekdays TEXT NOT NULL DEFAULT '0,1,2,3,4,5',
    requires_approval INTEGER NOT NULL DEFAULT 1,
    is_active INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
    UNIQUE (branch_id, name)
);

CREATE TABLE IF NOT EXISTS service_machines (
    service_id BIGINT NOT NULL REFERENCES services(id) ON DELETE CASCADE,
    machine_id BIGINT NOT NULL REFERENCES machines(id) ON DELETE CASCADE,
    PRIMARY KEY (service_id, machine_id)
);

CREATE TABLE IF NOT EXISTS service_instructors (
    service_id BIGINT NOT NULL REFERENCES services(id) ON DELETE CASCADE,
    instructor_id BIGINT NOT NULL REFERENCES instructors(id) ON DELETE CASCADE,
    PRIMARY KEY (service_id, instructor_id)
);

CREATE TABLE IF NOT EXISTS service_intake_fields (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_id BIGINT NOT NULL REFERENCES services(id) ON DELETE CASCADE,
    field_key TEXT NOT NULL,
    label TEXT NOT NULL,
    field_type TEXT NOT NULL DEFAULT 'text',
    help_text TEXT,
    placeholder TEXT,
    is_required INTEGER NOT NULL DEFAULT 0,
    options_json TEXT,
    price_adjustment_cents INTEGER NOT NULL DEFAULT 0,
    duration_adjustment_minutes INTEGER NOT NULL DEFAULT 0,
    sort_order INTEGER NOT NULL DEFAULT 0,
    is_active INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
    UNIQUE (service_id, field_key)
);

CREATE TABLE IF NOT EXISTS bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_name TEXT NOT NULL,
    mobile_number TEXT NOT NULL,
    machine_id BIGINT NOT NULL REFERENCES machines(id),
    instructor_id BIGINT NOT NULL REFERENCES instructors(id),
    branch_id BIGINT NOT NULL REFERENCES branches(id),
    target_date TEXT NOT NULL,
    start_time TEXT NOT NULL,
    end_time TEXT NOT NULL,
    validation_status TEXT NOT NULL DEFAULT 'Pending',
    student_user_id BIGINT REFERENCES users(id),
    notes TEXT,
    review_notes TEXT,
    reviewed_by BIGINT REFERENCES users(id),
    reviewed_at TEXT,
    attendance_recorded_by BIGINT REFERENCES users(id),
    attendance_recorded_at TEXT,
    cancelled_at TEXT,
    whatsapp_sent INTEGER NOT NULL DEFAULT 0,
    service_id BIGINT REFERENCES services(id),
    service_name TEXT,
    service_price_cents INTEGER NOT NULL DEFAULT 0,
    currency TEXT NOT NULL DEFAULT 'INR',
    buffer_before_minutes INTEGER NOT NULL DEFAULT 0,
    buffer_after_minutes INTEGER NOT NULL DEFAULT 0,
    calendar_revision INTEGER NOT NULL DEFAULT 1,
    series_id TEXT,
    repeat_rule TEXT,
    allow_double_booking INTEGER NOT NULL DEFAULT 0,
    series_position INTEGER NOT NULL DEFAULT 1,
    series_count INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
    source_reference TEXT UNIQUE,
    CHECK (validation_status IN ('Pending', 'Approved', 'Not Confirmed', 'Rejected',
        'Cancelled', 'Completed', 'No-show', 'Running Late', 'Arrived',
        'Rescheduled', 'No Action'))
);

CREATE TABLE IF NOT EXISTS booking_services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL REFERENCES bookings(id) ON DELETE CASCADE,
    service_id BIGINT REFERENCES services(id),
    service_name TEXT NOT NULL,
    duration_minutes INTEGER NOT NULL,
    price_cents INTEGER NOT NULL DEFAULT 0,
    currency TEXT NOT NULL DEFAULT 'INR',
    sort_order INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS booking_intake_values (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL REFERENCES bookings(id) ON DELETE CASCADE,
    field_id BIGINT REFERENCES service_intake_fields(id),
    field_key TEXT NOT NULL,
    field_label TEXT NOT NULL,
    value_text TEXT,
    file_name TEXT,
    file_path TEXT,
    mime_type TEXT,
    file_size BIGINT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
    UNIQUE (booking_id, field_id)
);

CREATE TABLE IF NOT EXISTS client_profiles (
    user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    admission_number TEXT,
    secondary_phone TEXT,
    secondary_email TEXT,
    birthday TEXT,
    gender TEXT,
    zip_code TEXT,
    city TEXT,
    street TEXT,
    internal_notes TEXT,
    tags TEXT,
    reminders_enabled INTEGER NOT NULL DEFAULT 1,
    preferred_channel TEXT NOT NULL DEFAULT 'email',
    updated_by BIGINT REFERENCES users(id),
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
    source_reference TEXT
);

-- Existing PostgreSQL databases created by the first migration schema need
-- this additive column too. It is safe to run on every application start.
ALTER TABLE client_profiles
    ADD COLUMN IF NOT EXISTS admission_number TEXT;

CREATE TABLE IF NOT EXISTS instructor_weekly_availability (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instructor_id BIGINT NOT NULL REFERENCES instructors(id) ON DELETE CASCADE,
    weekday INTEGER NOT NULL CHECK (weekday BETWEEN 0 AND 6),
    start_time TEXT NOT NULL,
    end_time TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
    UNIQUE (instructor_id, weekday, start_time, end_time),
    CHECK (start_time < end_time)
);

CREATE TABLE IF NOT EXISTS instructor_time_off (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instructor_id BIGINT NOT NULL REFERENCES instructors(id) ON DELETE CASCADE,
    target_date TEXT NOT NULL,
    start_time TEXT NOT NULL,
    end_time TEXT NOT NULL,
    reason TEXT,
    notes TEXT,
    series_id TEXT,
    repeat_rule TEXT,
    series_position INTEGER NOT NULL DEFAULT 1,
    series_count INTEGER NOT NULL DEFAULT 1,
    calendar_revision INTEGER NOT NULL DEFAULT 1,
    created_by BIGINT REFERENCES users(id),
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
    source_reference TEXT UNIQUE
);

CREATE TABLE IF NOT EXISTS default_lunch_exceptions (
    instructor_id BIGINT NOT NULL REFERENCES instructors(id) ON DELETE CASCADE,
    target_date TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
    PRIMARY KEY (instructor_id, target_date)
);

CREATE TABLE IF NOT EXISTS default_break_exceptions (
    instructor_id BIGINT NOT NULL REFERENCES instructors(id) ON DELETE CASCADE,
    target_date TEXT NOT NULL,
    break_kind TEXT NOT NULL CHECK (break_kind IN ('breakfast', 'lunch', 'tea')),
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
    PRIMARY KEY (instructor_id, target_date, break_kind)
);

CREATE TABLE IF NOT EXISTS booking_slots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instructor_id BIGINT NOT NULL REFERENCES instructors(id) ON DELETE CASCADE,
    machine_id BIGINT NOT NULL REFERENCES machines(id),
    branch_id BIGINT NOT NULL REFERENCES branches(id),
    target_date TEXT NOT NULL,
    start_time TEXT NOT NULL,
    end_time TEXT NOT NULL,
    notes TEXT,
    series_id TEXT,
    repeat_rule TEXT,
    series_position INTEGER NOT NULL DEFAULT 1,
    series_count INTEGER NOT NULL DEFAULT 1,
    calendar_revision INTEGER NOT NULL DEFAULT 1,
    created_by BIGINT REFERENCES users(id),
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
    source_reference TEXT UNIQUE
);

CREATE TABLE IF NOT EXISTS notification_queue (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL REFERENCES bookings(id) ON DELETE CASCADE,
    channel TEXT NOT NULL,
    event_type TEXT NOT NULL,
    destination TEXT NOT NULL,
    scheduled_for TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'queued',
    attempts INTEGER NOT NULL DEFAULT 0,
    last_error TEXT,
    sent_at TEXT,
    locked_at TEXT,
    next_attempt_at TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
    UNIQUE (booking_id, channel, event_type, scheduled_for)
);

CREATE TABLE IF NOT EXISTS audit_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id BIGINT REFERENCES users(id),
    booking_id BIGINT REFERENCES bookings(id),
    event_type TEXT NOT NULL,
    details TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text
);

CREATE TABLE IF NOT EXISTS student_instructor_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_user_id BIGINT NOT NULL REFERENCES users(id),
    instructor_id BIGINT NOT NULL REFERENCES instructors(id),
    assigned_by BIGINT REFERENCES users(id),
    is_active INTEGER NOT NULL DEFAULT 1,
    assigned_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
    ended_at TEXT,
    UNIQUE (student_user_id, instructor_id)
);

CREATE TABLE IF NOT EXISTS schema_migrations (
    migration_key TEXT PRIMARY KEY,
    applied_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text
);

CREATE INDEX IF NOT EXISTS idx_bookings_date_branch ON bookings(target_date, branch_id);
CREATE INDEX IF NOT EXISTS idx_bookings_instructor_status ON bookings(instructor_id, target_date, validation_status);
CREATE INDEX IF NOT EXISTS idx_bookings_student ON bookings(student_user_id, target_date);
CREATE INDEX IF NOT EXISTS idx_bookings_series ON bookings(series_id);
CREATE INDEX IF NOT EXISTS idx_booking_services_booking ON booking_services(booking_id);
CREATE INDEX IF NOT EXISTS idx_audit_booking ON audit_events(booking_id);
CREATE INDEX IF NOT EXISTS idx_services_branch_active ON services(branch_id, is_active);
CREATE INDEX IF NOT EXISTS idx_time_off_instructor_date ON instructor_time_off(instructor_id, target_date);
CREATE INDEX IF NOT EXISTS idx_time_off_series ON instructor_time_off(series_id);
CREATE INDEX IF NOT EXISTS idx_notifications_due ON notification_queue(status, scheduled_for);
CREATE INDEX IF NOT EXISTS idx_assignments_instructor_active ON student_instructor_assignments(instructor_id, is_active);
CREATE INDEX IF NOT EXISTS idx_assignments_student_active ON student_instructor_assignments(student_user_id, is_active);
CREATE INDEX IF NOT EXISTS idx_weekly_availability_instructor ON instructor_weekly_availability(instructor_id, weekday);
CREATE INDEX IF NOT EXISTS idx_client_profiles_reminders ON client_profiles(reminders_enabled, preferred_channel);

COMMIT;
